
package src.model.classroom;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * Model class for classroom data.
 * Aligned with the 'rooms' table schema and RoomView requirements.
 */
public class Classroom {
    // Properties corresponding to database columns
    private final StringProperty roomId;        // Corresponds to room_id (VARCHAR)
    private final StringProperty code;          // Corresponds to code (VARCHAR)
    private final StringProperty roomName;      // Corresponds to room_name (VARCHAR)
    private final IntegerProperty floor;        // Corresponds to floor (INT)
    private final IntegerProperty capacity;     // Corresponds to capacity (INT)
    private final StringProperty status;        // Corresponds to status (VARCHAR)
    private final StringProperty roomType;      // Corresponds to room_type (VARCHAR)

    // Property for TableView sequence number (STT), not in DB
    private final IntegerProperty stt;

    /**
     * Default constructor for creating new instances, e.g., from a form.
     */
    public Classroom() {
        this.roomId = new SimpleStringProperty(null); // Typically generated by DB or set later
        this.code = new SimpleStringProperty();
        this.roomName = new SimpleStringProperty();
        this.floor = new SimpleIntegerProperty();
        this.capacity = new SimpleIntegerProperty();
        this.status = new SimpleStringProperty();
        this.roomType = new SimpleStringProperty();
        this.stt = new SimpleIntegerProperty(0); // Default STT
    }


    /**
     * Constructor to initialize Classroom with all properties.
     * @param stt Sequence number for display
     * @param roomId Unique ID of the room (from room_id)
     * @param code Code of the room (from code)
     * @param roomName Name of the room (from room_name)
     * @param floor Floor number (from floor)
     * @param capacity Capacity of the room (from capacity)
     * @param status Status of the room (from status)
     * @param roomType Type of the room (from room_type)
     */
    public Classroom(int stt, String roomId, String code, String roomName, int floor, int capacity, String status, String roomType) {
        this.stt = new SimpleIntegerProperty(stt);
        this.roomId = new SimpleStringProperty(roomId);
        this.code = new SimpleStringProperty(code);
        this.roomName = new SimpleStringProperty(roomName);
        this.floor = new SimpleIntegerProperty(floor);
        this.capacity = new SimpleIntegerProperty(capacity);
        this.status = new SimpleStringProperty(status);
        this.roomType = new SimpleStringProperty(roomType);
    }

    // --- Getters for property values ---
    public int getid() { return stt.get(); }
    public String getRoomId() { return roomId.get(); }
    public String getCode() { return code.get(); }
    public String getRoomName() { return roomName.get(); }
    public int getFloor() { return floor.get(); }
    public int getCapacity() { return capacity.get(); }
    public String getStatus() { return status.get(); }
    public String getRoomType() { return roomType.get(); }

    // --- Setters for property values ---
    public void setStt(int stt) { this.stt.set(stt); }
    public void setRoomId(String roomId) { this.roomId.set(roomId); }
    public void setCode(String code) { this.code.set(code); }
    public void setRoomName(String roomName) { this.roomName.set(roomName); }
    public void setFloor(int floor) { this.floor.set(floor); }
    public void setCapacity(int capacity) { this.capacity.set(capacity); }
    public void setStatus(String status) { this.status.set(status); }
    public void setRoomType(String roomType) { this.roomType.set(roomType); }

    // --- Property getters for JavaFX binding ---
    public IntegerProperty sttProperty() { return stt; }
    public StringProperty roomIdProperty() { return roomId; }
    public StringProperty codeProperty() { return code; }
    public StringProperty roomNameProperty() { return roomName; }
    public IntegerProperty floorProperty() { return floor; }
    public IntegerProperty capacityProperty() { return capacity; }
    public StringProperty statusProperty() { return status; }
    public StringProperty roomTypeProperty() { return roomType; }

    @Override
    public String toString() {
        return "Classroom{" +
                "stt=" + stt.get() +
                ", roomId='" + roomId.get() + '\'' +
                ", code='" + code.get() + '\'' +
                ", roomName='" + roomName.get() + '\'' +
                ", floor=" + floor.get() +
                ", capacity=" + capacity.get() +
                ", status='" + status.get() + '\'' +
                ", roomType='" + roomType.get() + '\'' +
                '}';
    }
}

